Repository Team-ToYou/ToYou-Android, pull requests merged in 2024-07, with the labels that each got.

#20 [refactor] 패키지 구조 변경에 따른 리팩토링
  app/src/main/java/com/toyou/toyouandroid/model/FriendListModel.kt
  app/src/main/java/com/toyou/toyouandroid/model/PreviewCardModel.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/home/CardFragment.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/home/CreateFragment.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/home/PreviewFragment.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/home/adapter/CardPreviewListAdapter.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/viewmodel/SocialViewModel.kt
Labels: ♻️ refactor

#22 Feature/social
  app/src/main/res/drawable/plus_social.xml
  app/src/main/res/drawable/send_card.xml
  app/src/main/res/drawable/social_ballon.xml
  app/src/main/res/drawable/social_balloon.xml
  app/src/main/res/drawable/social_char.xml
  app/src/main/res/drawable/social_imoge.xml
  app/src/main/res/layout/fragment_question_content.xml
  app/src/main/res/layout/fragment_question_type.xml
  app/src/main/res/layout/fragment_send.xml
  app/src/main/res/layout/fragment_send_final.xml
Labels: 🎨 design

#29 Feature/20240724
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/toyou/toyouandroid/ToYouApplication.kt
  app/src/main/java/com/toyou/toyouandroid/model/NoticeItem.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/base/MainActivity.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/emotionstamp/HomeOptionFragment.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/home/HomeBottomSheetFragment.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/home/HomeBottomSheetItemDecoration.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/home/HomeFragment.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/mypage/MypageFragment.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/notice/NoticeAdapter.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/notice/NoticeFragment.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/onboarding/LoginFragment.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/onboarding/SignupAgreeFragment.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/onboarding/SignupNicknameFragment.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/onboarding/SignupNicknameViewModel.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/fragment/onboarding/SignupStatusFragment.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/viewmodel/HomeOptionViewModel.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/viewmodel/HomeResultViewModel.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/viewmodel/HomeViewModel.kt
  app/src/main/java/com/toyou/toyouandroid/presentation/viewmodel/ViewModelManager.kt
  app/src/main/java/com/toyou/toyouandroid/utils/SwipeToDeleteNotice.kt
  app/src/main/res/drawable/background_bottom_sheet.xml
  app/src/main/res/drawable/home_bottom_sheet_card.png
  app/src/main/res/drawable/kakao_btn.png
  app/src/main/res/drawable/kakao_btn.xml
  app/src/main/res/drawable/kakao_talk.xml
  app/src/main/res/drawable/next_button_enabled_roundly.xml
  app/src/main/res/drawable/next_button_roundly.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_bottom_sheet.xml
  app/src/main/res/layout/fragment_home_option.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_signupagree.xml
  app/src/main/res/layout/fragment_signupnickname.xml
  app/src/main/res/layout/fragment_signupstatus.xml
  app/src/main/res/layout/fragment_terms_of_use.xml
  app/src/main/res/layout/item_home_bottom_sheet.xml
  app/src/main/res/layout/item_notice_friend_request_accepted.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: ✨ feature
